version: "2"

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: dbpass1234
      MYSQL_DATABASE: blocadmin
      MYSQL_USER: blocadmin_user
      MYSQL_PASSWORD: bloc1admin2pass3
  app:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    depends_on:
      - db
    links:
      - db
    ports:
      - "3003:3000"
    environment:
      RAILS_ENV: production
      MYSQL_DATABASE: blocadmin
      MYSQL_USER: blocadmin_user
      MYSQL_PASSWORD: bloc1admin2pass3

