version: "3"

volumes:
  db-data:
    external: false

services:
  postgres-db:
    image: postgres:12
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: always
    env_file: docker.env
    expose:
      - 5432
    command: -h "*"
  bloc_app:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    depends_on:
      - postgres-db
    links:
      - postgres-db
    ports:
      - "127.0.0.1:3000:3000"
    env_file: docker.env

